micronaut:
  application:
    name: keyManagerRest

grpc:
  client:
    plaintext: true
    max-retry-attemps: 10
  channels:
    KeyManager:
      address: '${KEY_MANAGER_HOST:host.docker.internal}:${KEY_MANAGER_PORT:50051}' # docker
      # address: '${KEY_MANAGER_HOST:localhost}:${KEY_MANAGER_PORT:50051}' # local
  server:
    health:
      enabled: true

endpoints:
  health:
    enabled: true
    sensitive: false
    details-visible: ANONYMOUS

jackson:
  serialization:
    writeDatesAsTimestamps: false